version: "3"
services: 
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: always
    volumes:
      - ${DATADIR}/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=9000
      - DECONZ_WS_PORT=9443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
    ports:
      - 9000:9000
      - 9443:9443
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    ports:
     - 7000:8123
    volumes:
      - ${DATADIR}/homeassistant:/config
    environment:
      - TZ=${TZ}
    restart: always
